### PR TITLE
Add required user features to devise.

### PR DESCRIPTION
**Pull request by no-reply**
Remaining questions:

  - Do all of these features belong here, or should some go in MIRA?
  - How do we want to test these?

### CODE REVIEW

**Comment by no-reply** [comment]
@mark-dce did we have a solution for `email`?

**Comment by no-reply** [comment]
The problem with email is that `:validatable` is intended only to validate it and password; not as a general validation add-on. Even though we've set `:username` as the auth key, the validations are looking for email and hitting no method error. I've just removed validatable--it doesn't seem relevant for ldap authentication, anyway.

**Comment by mark-dce** [comment]
agreed - we shouldn't need to validate any LDAP provided fields within the application.  Any checks that need to happen should occur when the user is set up in LDAP.

**Comment by mark-dce** [comment]
If we're using the institution's LDAP, I don't think we want devise's `:registerable` or `:recoverable` but I'm going to merge this for now and confirm the need for those two later to keep us moving for now.

**Pull request merged**
